// Generated by CoffeeScript 1.6.3
(function() {
  var PEG, Q, RuleParser, cache, fs, overrideAction, uuid, _;

  PEG = require('pegjs');

  overrideAction = require('pegjs-override-action');

  fs = require('fs');

  Q = require('q');

  _ = require('underscore');

  uuid = require('uuid');

  cache = require('./cache');

  module.exports = RuleParser = (function() {
    function RuleParser() {}

    RuleParser.setData = function(data) {
      return this.data = data;
    };

    RuleParser.executeRule = function(ruleData, rule) {
      var $value, $variable, id, newData, parser, replaceWith, variableSet, variableValues, _i, _len, _ref;
      if (!this.data) {
        throw new Error('Tester is not ready. Please check tester.ready()');
      }
      id = uuid.v4();
      replaceWith = [];
      cache[id] = ruleData;
      variableSet = '';
      variableValues = [void 0, void 0, void 0, void 0, void 0];
      _ref = ruleData.$variables;
      for ($value = _i = 0, _len = _ref.length; _i < _len; $value = ++_i) {
        $variable = _ref[$value];
        replaceWith.push("/ '" + $variable + "' ");
        variableValues.push($variable);
        variableSet += "\t\t" + $variable + " = cache.$variables['" + variable + "'],\n";
      }
      newData = this.data.replace("// $variables", replaceWith);
      parser = PEG.buildParser(newData, {
        plugins: [overrideAction],
        overrideActionPlugin: {
          initializer: "					var cache = require('" + __dirname + "/cache')['" + id + "'],						data = cache.data,						newData = cache.newData,						auth = cache.auth,						" + variableSet + "						root = cache.root;					",
          rules: {
            rawObject: variableValues
          }
        }
      });
      return parser.parse(rule);
    };

    RuleParser.ready = Q.nfcall(fs.readFile, __dirname + '/grammar.pegjs', 'utf8').then(function(data) {
      return RuleParser.setData(data);
    });

    return RuleParser;

  })();

}).call(this);
